import Head from "next/head";
import { Inter } from "next/font/google";
import React from "react";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const fileInputRef = React.useRef();

  const submitHandler = async (event) => {
    event.preventDefault();
    try {
      const formData = new FormData();
      formData.append("file", fileInputRef.current.files[0]);
  
      const response = await fetch("/api/upload", {
        method: "POST",
        body: formData,
      });
  
      // The API response
      const data = await response.json();
      console.log(data); // Log the response from the API
    } catch (error) {
      console.log("error ", error)
    }
 
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <form onSubmit={submitHandler}>
            <input type="file" ref={fileInputRef} />
            <button type="submit">Upload</button>
          </form>
      
        
        </div>

    
      </main>
    </>
  );
}
